apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler-codespaces-7d779f
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: registry.k8s.io/kube-scheduler:v1.30.0
    command:
    - kube-scheduler
    - --kubeconfig=/etc/kubernetes/scheduler.kubeconfig
    - --leader-elect=false
    - --bind-address=0.0.0.0
    - --secure-port=10260         # <— добавили/заменили
    - --v=2
    volumeMounts:
    - name: kc
      mountPath: /etc/kubernetes/scheduler.kubeconfig
      subPath: scheduler.kubeconfig
      readOnly: true
  volumes:
  - name: kc
    hostPath:
      path: /etc/kubernetes
      type: Directory
