apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: kube-scheduler
    image: registry.k8s.io/kube-scheduler:v1.30.0
    command:
      - kube-scheduler
      - --kubeconfig=/etc/kubernetes/scheduler.conf
      - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
      - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
      - --leader-elect=false
      - --port=0
      - --secure-port=10259
    volumeMounts:
      - { name: cfg, mountPath: /etc/kubernetes }
  volumes:
    - { name: cfg, hostPath: { path: /etc/kubernetes } }
