apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: kube-controller-manager
    image: registry.k8s.io/kube-controller-manager:v1.30.0
    command:
      - kube-controller-manager
      - --kubeconfig=/etc/kubernetes/controller-manager.conf
      - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
      - --root-ca-file=/etc/kubernetes/pki/ca.crt
      - --leader-elect=false
      - --port=0
      - --secure-port=10257
    volumeMounts:
      - { name: pki, mountPath: /etc/kubernetes/pki, readOnly: true }
      - { name: cfg, mountPath: /etc/kubernetes }
  volumes:
    - { name: pki, hostPath: { path: /etc/kubernetes/pki } }
    - { name: cfg, hostPath: { path: /etc/kubernetes } }
