apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels: { tier: control-plane, component: kube-apiserver }
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: kube-apiserver
    image: registry.k8s.io/kube-apiserver:v1.30.0
    command:
      - kube-apiserver
      - --advertise-address=10.0.12.142
      - --secure-port=6443
      - --etcd-servers=http://127.0.0.1:2379
      - --service-cluster-ip-range=10.0.0.0/24

      # строгая authN/authZ
      - --client-ca-file=/etc/kubernetes/pki/ca.crt
      - --anonymous-auth=false
      - --authorization-mode=Node,RBAC

      # ServiceAccount tokens
      - --service-account-issuer=https://kubernetes.default.svc.cluster.local
      - --service-account-key-file=/etc/kubernetes/pki/sa.pub
      - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key

      # TLS сервера apiserver
      - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
      - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    volumeMounts:
      - name: pki
        mountPath: /etc/kubernetes/pki
        readOnly: true
  volumes:
    - name: pki
      hostPath:
        path: /etc/kubernetes/pki
        type: Directory
