apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager-codespaces-7d779f
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: registry.k8s.io/kube-controller-manager:v1.30.0
    command:
    - kube-controller-manager
    - --kubeconfig=/etc/kubernetes/controller-manager.kubeconfig
    - --leader-elect=false
    - --service-cluster-ip-range=10.0.0.0/24
    - --cluster-name=kubernetes
    - --root-ca-file=/etc/kubernetes/pki/ca.crt
    - --service-account-private-key-file=/etc/kubernetes/pki/sa.key
    - --use-service-account-credentials=true
    - --v=2
    volumeMounts:
    - name: pki
      mountPath: /etc/kubernetes/pki
      readOnly: true
    - name: kc
      mountPath: /etc/kubernetes/controller-manager.kubeconfig
      subPath: controller-manager.kubeconfig
      readOnly: true
  volumes:
  - name: pki
    hostPath:
      path: /etc/kubernetes/pki
      type: Directory
  - name: kc
    hostPath:
      path: /etc/kubernetes
      type: Directory
